#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  ca.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/516f7572b04d204b4d9eb346356f1c8040ab611d1922c0ec2d1bf85192cf141c_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.example.com
    networks:
      - basic

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/msp/peerOrg1
    networks:
      - basic

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org1.example.com:5984
      - CORE_LEDGER_STATE_STATEDATABASE=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchuser
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchpass
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
      - couchdb0.org1.example.com
    networks:
      - basic

  couchdb0.org1.example.com:
    container_name: couchdb0.org1.example.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchuser
      - COUCHDB_PASSWORD=couchpass
    ports:
      - 5984:5984
    networks:
      - basic

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.example.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.org1.example.com:5984
      - CORE_LEDGER_STATE_STATEDATABASE=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchuser
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchpass
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
      - couchdb1.org1.example.com
    networks:
      - basic

  couchdb1.org1.example.com:
    container_name: couchdb1.org1.example.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchuser
      - COUCHDB_PASSWORD=couchpass
    ports:
      - 6984:5984
    networks:
      - basic

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.example.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org2.example.com:5984
      - CORE_LEDGER_STATE_STATEDATABASE=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchuser
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchpass
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
      - couchdb0.org2.example.com
    networks:
      - basic

  couchdb0.org2.example.com:
    container_name: couchdb0.org2.example.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchuser
      - COUCHDB_PASSWORD=couchpass
    ports:
      - 7984:5984
    networks:
      - basic
  
  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.example.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.org2.example.com:5984
      - CORE_LEDGER_STATE_STATEDATABASE=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchuser
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchpass
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
      - couchdb1.org2.example.com
    networks:
      - basic

  couchdb1.org2.example.com:
    container_name: couchdb1.org2.example.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchuser
      - COUCHDB_PASSWORD=couchpass
    ports:
      - 8984:5984
    networks:
      - basic

  kafka0.example.com:
    container_name: kafka0.example.com
    image: hyperledger/fabric-kafka
    environment: 
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_MESSAGE_MAX_BYTES=134217728
      - KAFKA_REPLICA_FETCH_MAX_BYTES=134217728
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zoo0.example.com:2181,zoo1.example.com:2181,zoo2.example.com:2181
    ports:
      - 9092:9092
      - 9093:9093
    networks:
      - basic
    depends_on: 
      - zoo0.example.com
      - zoo1.example.com
      - zoo2.example.com
      
  kafka1.example.com:
    container_name: kafka1.example.com
    image: hyperledger/fabric-kafka
    environment: 
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_MESSAGE_MAX_BYTES=134217728
      - KAFKA_REPLICA_FETCH_MAX_BYTES=134217728
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zoo0.example.com:2181,zoo1.example.com:2181,zoo2.example.com:2181
    ports:
      - 19092:9092
      - 19093:9093
    networks:
      - basic
    depends_on: 
      - zoo0.example.com
      - zoo1.example.com
      - zoo2.example.com

  zoo0.example.com:
    container_name: zoo0.example.com
    image: hyperledger/fabric-zookeeper
    environment: 
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo0.example.com:2888:3888,server2=zoo1.example.com:2888:3888,server3=zoo2.example.com:2888:3888
    ports: 
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks: 
      - basic

  zoo1.example.com:
    container_name: zoo1.example.com
    image: hyperledger/fabric-zookeeper
    environment: 
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zoo0.example.com:2888:3888,server2=zoo1.example.com:2888:3888,server3=zoo2.example.com:2888:3888
    ports: 
      - 12181:2181
      - 12888:2888
      - 13888:3888
    networks: 
      - basic

  zoo2.example.com:
    container_name: zoo2.example.com
    image: hyperledger/fabric-zookeeper
    environment: 
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zoo0.example.com:2888:3888,server2=zoo1.example.com:2888:3888,server3=zoo2.example.com:2888:3888
    ports: 
      - 22181:2181
      - 22888:2888
      - 23888:3888
    networks: 
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./config:/etc/hyperledger/configtx
    networks:
        - basic

